CAPL Tables {data-navmenu="Bank Profit and Capital"}
=====================================

```{r}
#### Fourth we render everything in a navbar

shinyUI(
  fluidPage(
    navbarPage("",
               tabPanel(
                 div(style="display: inline-block; align: center;",
                     shinyWidgets::dropdown(label='B4 SA Floor', 
                                            fluidRow( column(10,offset=0, 
                                                             div(style = "",
                                                                 tags$h4(""),
                                                                 br(),
                                                                 radioGroupButtons(inputId = 'B4SAFloorCAPLTable', individual = T,
                                                                                     choices=c("B4 SA Floor: Yes","B4 SA Floor: No"), 
                                                                                     selected = "B4 SA Floor: Yes", checkIcon = list(yes = tags$i(class = "fa fa-circle", 
                                                                                     style = "color: steelblue"), 
                                                                                     no = tags$i(class = "fa fa-circle-o", 
                                                                                     style = "color: steelblue")))))), 
                                            circle = F, status = "primary", icon = icon("formula"),
                                            width = "200px",tooltip = tooltipOptions(title = "Click to modify inputs")))),

               tabPanel(
                 div(style="display: inline-block; align: center;",
                     shinyWidgets::dropdown(label = 'Scenario',
                                            fluidRow(column(10,offset=0,
                                                            div(style = "padding: 0px 0px; margin-left:0.1%",
                                                                tags$h4(""),
                                                                br(),
                                                                uiOutput(outputId = "scenariosSelectCAPLTable"),
                                                                bsTooltip(id = "Scenario", title = " ",
                                                                          placement = "top", trigger = "hover")))),
                                            circle = F, status = "primary",
                                            icon = icon("time"), width = "200px",
                                            tooltip = tooltipOptions(title = "Click to modify inputs"))))
               
    ), 
    HTML("<script>var parent = document.getElementsByClassName('navbar-nav');
         parent[0].insertAdjacentHTML( 'afterend', '<ul class=\"nav navbar-nav navbar-right\"><li class=\"disabled\"><a href=\"#\">v0.1</a></li></ul>' );</script>")
    ))

output$scenariosSelectCAPLTable <- renderUI({
  tagList(
    #selectInput(inputId = 'ScenarioCAPLTable', label = ' ', choices = unique(resultsFiltered()$Scenario), selected = grep("Baseline|baseline", unique(resultsFiltered()$Scenario), value = T))
    radioGroupButtons(inputId = 'ScenarioCAPLTable', individual = T, choices=unique(resultsFiltered()$Scenario), 
                                                                         selected = grep("Baseline|baseline", unique(resultsFiltered()$Scenario), value = T), 
                                                                                                     checkIcon = list(yes = tags$i(class = "fa fa-circle", 
                                                                         style = "color: steelblue"), 
                                                                         no = tags$i(class = "fa fa-circle", 
                                                                         style = "color: white")))
    )
  })
outputOptions(x = output, name = "scenariosSelectCAPLTable", suspendWhenHidden = FALSE)



```

Row {data-height=80}
-------------------------------------
  
### <span style="color:`r valueBoxTextColor`"></span>

```{r}
renderValueBox({
  valueBox(tags$p(paste('Scenario:', 
                         c('EBA Adverse','EBA Baseline','OSIS Extreme','OSIS Optimal','CCAR Adverse','CCAR Baseline')[which(input$ScenarioCAPLTable==unique(resultsFiltered()$Scenario))]), style = "font-size: 50%;"))
})
```




Row
-----------------------------------

### <span style="color:`r borderTextColor`">Capital and P&L Projection Before Risk Distribution</span>

```{r}
transactionOutputTable <- reactive({
  input$renewValue
#input$SwitchIRB
#input$B4SAFloorCAPLTable
#Calculate actual required capital with or without B4 SA floor
results <- copy(resultsFiltered())

results[PortfolioLabel=="SA", RW := RWA_SA_Actual/EAD]
results[PortfolioLabel=="SA", RWA := RWA_SA_Actual]
results[PortfolioLabel=="SA", CapitalCharge_Required := RWA_SA_Actual * CT1_Target]
if(input$B4SAFloorCAPLTable=="B4 SA Floor: No") {
  results[PortfolioLabel=="IRB", RW := RWA_IRBA_Actual/EAD]
  results[PortfolioLabel=="IRB", RWA := RWA_IRBA_Actual]
  results[PortfolioLabel=="IRB", CapitalCharge_Required := RWA_IRBA_Actual * CT1_Target]
} else {
  results[PortfolioLabel=="IRB", RW := RWA_IRBA_Floor/EAD]
  results[PortfolioLabel=="IRB", RWA := RWA_IRBA_Floor]
  results[PortfolioLabel=="IRB", CapitalCharge_Required := RWA_IRBA_Floor * CT1_Target]
} 

#Risk weight of retained senior tranche
results[PortfolioLabel=="IRB", RW_RetainedSenior := 0.07]
results[PortfolioLabel=="IRB" & DateYQ>2020, RW_RetainedSenior := 0.15] #Check intro timeline of SEC IRB, here ignore STS
results[PortfolioLabel=="SA", RW_RetainedSenior := 0.2]

#Repline P&L and ROE
results[, ExpectedLossPerc := ECL_1Y/EAD] #PIT
results[, CapitalChargePerc := RW / 12.5] #100% RW = 0.08 capital charge, note that capitalcharge is based on actual CT1 ratio of 0.1
results[, KIRB := CapitalChargePerc + ExpectedLossPerc]

#Size first loss piece in percentage of total limit as multiple of KIRB
results[, SizeFLP := pmax(pmin(KIRB, 0.15), 0.025)] 
#Equal to KIRB subject to cap and floor. TO DO: Check why so many KIRB>15%, is that due to defaulters?
#TO DO: current SizeFLP varies with rating migration, is this reasonable?

results[, GII := UndrawnAmount*committment_fee + DrawnAmount*currentinterestrate/4]# quarterlyTO DO: deduct defaulted amounts
results[, NII := GII - FTP_Rate*DrawnAmount*currentinterestrate/4]
results[, PreTaxProfit := (1 - CostIncomeRatio)*NII - (Stage1ECLFlow + Stage2ECLFlow + Stage3ECL)] 
results[, PostTaxProfit := PreTaxProfit * (1 - TaxRate)] 
results[, ROE := 4*PostTaxProfit / CapitalCharge_Required] #annualized, ROE based on required capital

#Calculate available capital by business: assume initial allocation of CT1 capital is proportional to RWA
# poolDate <- min(results$DateYQ)
# results[, BusinessID := paste0(BankNameShort, "_", Country, "_", ExposureReduced, "_", PortfolioLabel)] #"Business" includes all vintages, required for available capital
# results[, RWA_initial_mod := sum(RWA[DateYQ==poolDate]), by=c("Scenario", "BusinessID")]  #modelled RWA, TO DO: investigate main source of difference in proprocess
# results[, CT1_AMT_initial := CT1_fully*RWA_initial_mod] #use modelled RWA for consistency
# 
# #Calculate capital generation and return on available capital by business
# resultsBusiness <- results[, .(PostTaxProfit = sum(PostTaxProfit),
#                                RWA_initial_mod = min(RWA_initial_mod),
#                                RWA=sum(RWA),
#                                CT1_AMT_initial = min(CT1_AMT_initial),
#                                Dividend=min(Dividend)), by=c("Scenario", "BusinessID", "DateYQ")] #quarterly profit aggregated over all vintages
# 
# resultsBusiness[, DividendPayout := pmax(PostTaxProfit * Dividend, 0)]
# resultsBusiness[, CapitalIncrement := PostTaxProfit - DividendPayout] #quarterly profit post div
# resultsBusiness[, CT1_AMT_avail := CT1_AMT_initial + cumsum(CapitalIncrement), by=c("Scenario", "BusinessID")] #Available CT1
# resultsBusiness[, CT1_avail := CT1_AMT_avail/RWA]
# resultsBusiness[, ROE_avail := 4*PostTaxProfit / CT1_AMT_avail]  

########################################################
#Calculate impact of risk transfer strategies, After Risk Transfer ART. Notation: exposures and measures without suffix indicate no risk distribution. _ART indicated numbers 

results[, TotalLimit_ART := TotalLimit * (1 - PercSynd - PercDebtFund)]
results[, EAD_ART := EAD * (1 - PercSynd - PercDebtFund)] #synthetic does not change EAD nor TL
results[, RWA_ART := RWA * (1 - PercSynd - PercDebtFund - PercCRT) + TotalLimit*PercCRT*RW_RetainedSenior]
results[, Stage3ECL_ART :=  Stage3ECL*(1 - PercSynd - PercDebtFund - PercCRT)] #Flow and stock, assume synthetic CRT absorbs all losses
results[, Stage2ECL_ART :=  Stage2ECL*(1 - PercSynd - PercDebtFund)] #assume stage 1 and 2 ECL unchanged by synthetic CRT
results[, Stage1ECL_ART :=  Stage1ECL*(1 - PercSynd - PercDebtFund)]
results[, Stage1ECLFlow_ART := c(0,diff(Stage1ECL_ART)), by=c("BankNameShort", "Scenario", "LoanIdentifier")] #allow for more than one bank in results table
results[, Stage2ECLFlow_ART := c(0,diff(Stage2ECL_ART)), by=c("BankNameShort", "Scenario", "LoanIdentifier")]

results[, GII_ART := ((UndrawnAmount*committment_fee + DrawnAmount*currentinterestrate)*(1 - PercSynd - PercDebtFund) + TotalLimit*PercDebtFund*debtfund_fee)/4]#TO DO: deduct defaulted amounts
results[, CRT_cost := TotalLimit*PercCRT*SizeFLP*SpreadFLP/4] #TO DO: link funding cost to market spreads
results[, NII_ART := GII_ART - FTP_Rate*(1 - PercSynd - PercDebtFund)*DrawnAmount*currentinterestrate/4 - CRT_cost] # TO DO: FTP_Rate defined as IntExp as perc of GII, maybe other definitions are more intuitive 

results[, PreTaxProfit_ART := (1 - CostIncomeRatio)*NII_ART - (Stage1ECLFlow_ART + Stage2ECLFlow_ART + Stage3ECL_ART)] 
results[, PostTaxProfit_ART := PreTaxProfit_ART * (1 - TaxRate)] 
results[, CapitalCharge_Required_ART := RWA_ART *CT1_Target]
results[, ROE_ART := 4*PostTaxProfit_ART / CapitalCharge_Required_ART]

#Calculate capital generation as above with RWA_ART and PortTaxProfit_ART


#####

#Total cumulative loss
results[, CumulativeLoss := cumsum(MarginalEL), by=c("BankNameShort", "Scenario", "LoanIdentifier")]#Vintage repline cumulative loss
results[, InitialLimit := data.table::first(TotalLimit), by=c("BankNameShort", "Scenario", "LoanIdentifier")]
results[, InitialLimit_ART := data.table::first(TotalLimit_ART), by=c("BankNameShort", "Scenario", "LoanIdentifier")]
results[, CumLossPercInitialLimit := CumulativeLoss/InitialLimit]
#Selected portfolio cumulative loss
results[, CumulativeLoss_ART := CumulativeLoss * (1 - PercSynd - PercDebtFund - PercCRT)] 
results[, CumLossPercInitialLimit_ART := CumulativeLoss_ART/InitialLimit_ART]

#aggregate
DTSub <- results[Scenario==input$ScenarioCAPLTable,
                    .(EAD_BRT                    = sum(EAD, na.rm = T), #still missing marginalEL_ART and TLAC cost saving: should they be included?
                      EAD_ART                    = sum(EAD_ART, na.rm = T), 
                      TotalLimit_BRT             = sum(TotalLimit, na.rm = T),
                      TotalLimit_ART             = sum(TotalLimit_ART, na.rm = T),
                      RWA_BRT                    = sum(RWA, na.rm = T),
                      RWA_ART                    = sum(RWA_ART, na.rm = T),
                      CapitalCharge_Required_BRT = sum(CapitalCharge_Required, na.rm = T),
                      CapitalCharge_Required_ART = sum(CapitalCharge_Required_ART, na.rm = T),
                      CRT_cost                   = sum(CRT_cost, na.rm = T),
                      Stage2ECLFlow_BRT          = sum(Stage2ECLFlow, na.rm = T),
                      Stage2ECLFlow_ART          = sum(Stage2ECLFlow_ART, na.rm = T),
                      Stage2Perc                 = 100 * weighted.mean(Rating7, TotalLimit, na.rm = T),
                      NII_BRT                    = sum(NII, na.rm = T),
                      NII_ART                    = sum(NII_ART, na.rm = T),
                      ROE_BRT                    = round(100 *weighted.mean(ROE, EAD, na.rm = T),2),
                      ROE_ART                    = round(100* weighted.mean(ROE_ART, EAD_ART, na.rm = T),2)),
                    by=c("DateYQ","BankNameShort")]
DTSub[ , LeverageRatio_BRT := round(CapitalCharge_Required_BRT / EAD_BRT * 100,2) ]                     
DTSub[ , LeverageRatio_ART := round(CapitalCharge_Required_ART / EAD_ART * 100,2) ]                     

myVector<-c('EAD_BRT','EAD_ART','TotalLimit_BRT','TotalLimit_ART','RWA_BRT','RWA_ART','CapitalCharge_Required_BRT','CapitalCharge_Required_ART',
            'CRT_cost','Stage2ECLFlow_BRT','Stage2ECLFlow_ART','NII_BRT','NII_ART')

  if(grepl(("ING|ABN|AMRO|Banco|Santander|Barclays|Pfandbriefbank|Rabobank"),input$bankDataSelectedSidebar)){
    
    }else{
      DTSub[, myVector] <-DTSub [, ..myVector]/1000
    }

DT_BRT <- subset(DTSub, select= c('DateYQ','BankNameShort', 'EAD_BRT', 'RWA_BRT','CapitalCharge_Required_BRT', 'Stage2Perc', 'Stage2ECLFlow_BRT', 'NII_BRT', 'ROE_BRT'))
DT_BRT <- melt(DT_BRT, id.vars= c('DateYQ','BankNameShort'))
DT_BRT <- dcast(DT_BRT, BankNameShort + variable  ~ DateYQ, value.var='value')
DT_BRT$variable <- c("EAD Total MM", "RWA Total MM", "CET1 Total MM", "IFRS9 Stage 2", "Stage2 ECL Flow Total MM", "NII Total MM", "ROE")

DT_ART <- subset(DTSub, select= c('DateYQ','BankNameShort', 'EAD_ART', 'RWA_ART', 'CapitalCharge_Required_ART', 'CRT_cost', 'Stage2ECLFlow_ART', 'NII_ART', 'ROE_ART'))
DT_ART <- melt(DT_ART, id.vars= c('DateYQ','BankNameShort'))
DT_ART <- dcast(DT_ART, BankNameShort + variable  ~ DateYQ , value.var='value')
DT_ART$variable <- c("EAD Total MM", "Total RWA After RT MM", "Total CT1 After RT MM", "Cost Risk Transfers MM", 
                         "Stage2 ECL Flow ART MM", "NII ART MM", "ROE ART")
library(scales)
euro <- dollar_format(prefix = "", suffix = "")#\u20ac
# Create tables
aggr <- 1
# 
# Total
DT_BRT[is.na(DT_BRT)] <- 0
DT_BRT_Table <- data.frame(DT_BRT)
DT_BRT_Table[,3:ncol(DT_BRT_Table)] <- NA
DT_BRT_Table[1,3:ncol(DT_BRT_Table)] <- paste0(euro(unlist(c(matrix(DT_BRT[1,3:ncol(DT_BRT)])))/aggr))
DT_BRT_Table[2,3:ncol(DT_BRT_Table)] <- paste0(euro(unlist(c(matrix(DT_BRT[2,3:ncol(DT_BRT)])))/aggr))
DT_BRT_Table[3,3:ncol(DT_BRT_Table)] <- paste0(euro(unlist(c(matrix(DT_BRT[3,3:ncol(DT_BRT)])))/aggr))
DT_BRT_Table[4,3:ncol(DT_BRT_Table)] <- paste0(round(unlist(c(matrix(DT_BRT[4,3:ncol(DT_BRT)]))),2),"%")
DT_BRT_Table[5,3:ncol(DT_BRT_Table)] <- paste0(euro(unlist(c(matrix(DT_BRT[5,3:ncol(DT_BRT)])))/aggr))
DT_BRT_Table[6,3:ncol(DT_BRT_Table)] <- paste0(euro(unlist(c(matrix(DT_BRT[6,3:ncol(DT_BRT)])))/aggr))
DT_BRT_Table[7,3:ncol(DT_BRT_Table)] <- paste0(round(unlist(c(matrix(DT_BRT[7,3:ncol(DT_BRT)]))),2),"%")

# ART
DT_ART_Table <- data.frame(DT_ART)
DT_ART_Table[,3:ncol(DT_ART_Table)] <- NA
DT_ART_Table[1,3:ncol(DT_ART_Table)] <- paste0(euro(unlist(c(matrix(DT_ART[1,3:ncol(DT_ART)])))/aggr))
DT_ART_Table[2,3:ncol(DT_ART_Table)] <- paste0(euro(unlist(c(matrix(DT_ART[2,3:ncol(DT_ART)])))/aggr))
DT_ART_Table[3,3:ncol(DT_ART_Table)] <- paste0(euro(unlist(c(matrix(DT_ART[3,3:ncol(DT_ART)])))/aggr))
DT_ART_Table[4,3:ncol(DT_ART_Table)] <- paste0(euro(unlist(c(matrix(DT_ART[4,3:ncol(DT_ART)])))/aggr))
DT_ART_Table[5,3:ncol(DT_ART_Table)] <- paste0(euro(unlist(c(matrix(DT_ART[5,3:ncol(DT_ART)])))/aggr))
DT_ART_Table[6,3:ncol(DT_ART_Table)] <- paste0(euro(unlist(c(matrix(DT_ART[6,3:ncol(DT_ART)])))/aggr))
DT_ART_Table[7,3:ncol(DT_ART_Table)] <- paste0(round(unlist(c(matrix(DT_ART[7,3:ncol(DT_ART)]))),2),"%")

DT_BRT_Table <- data.table(DT_BRT_Table)
DT_ART_Table <- data.table(DT_ART_Table)
  
colnames(DT_BRT_Table) <- paste0('<span style="color:',c("white"),'">', c(colnames(DT_BRT_Table)[1], substr(colnames(DT_BRT_Table)[2:length(colnames(DT_BRT_Table))], 2, 8)),'</span>')
   DT_BRT_Table <- DT::datatable(DT_BRT_Table,escape=F,options=list(searching=FALSE, scrollY='450px', scrollX=T, paging=F,bInfo=F)) %>%
   formatStyle(columns = c(0:ncol(DT_BRT_Table)), color = tableTextColor, backgroundColor = backgroundcolorTables)

colnames(DT_ART_Table) <- paste0('<span style="color:',c("white"),'">', c(colnames(DT_ART_Table)[1], substr(colnames(DT_ART_Table)[2:length(colnames(DT_ART_Table))], 2, 8)),'</span>')
   DT_ART_Table <- DT::datatable(DT_ART_Table,escape=F,options=list(searching=FALSE, scrollY='450px', scrollX=T, paging=F,bInfo=F)) %>%
   formatStyle(columns = c(0:ncol(DT_ART_Table)), color = tableTextColor, backgroundColor = backgroundcolorTables)
  
  return(list(DT_ART_Table = DT_ART_Table, DT_BRT_Table = DT_BRT_Table))
})

renderDataTable({
  transactionOutputTable()$DT_BRT_Table
  })


```

Row
-------------------------------------

### <span style="color:`r borderTextColor`">Capital and P&L Projection After Risk Distribution</span>

```{r}
renderDataTable({
   transactionOutputTable()$DT_ART_Table
  })

```
